name: Live Deployment via SSH

on:
    workflow_dispatch:
    # push:
    #   branches:
    #     - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: production

        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Execute deployment commands
          uses: appleboy/ssh-action@v0.1.3
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME || 'ubuntu' }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.SSH_PORT || 22 }}
            debug: true
            script: |
                whoami
                cd /var/www/html/fleetyes.com/htdocs
                git pull origin main
